---
# atd-fabric-provision-eapi.yml

- name: Deploy Configs
  hosts: ATD_FABRIC
  gather_facts: false
  tasks:

    - name: Deploy Configurations to Devices
      import_role:
        name: arista.avd.eos_config_deploy_eapi
